"""Export physical rollouts generated by the closed-loop SMP teacher.

Each row in the output NPZ is one post-transition simulator state.  Row zero is
the reset state and therefore has a zero action/reward; for every later row,
``action[t]`` is the policy action that produced that state from row ``t - 1``.
The exported state uses the MuJoCo convention: free-joint quaternion is wxyz,
free-joint angular velocity in ``qvel`` is expressed in the root body frame,
and joint order is the canonical SMP Go2 order.

Example
-------
    uv run python tools/smp_tools/teacher/export_teacher_rollouts.py \
      --checkpoint-file logs/rsl_rl/go2_smp_reference_teacher/.../model_15000.pt \
      --output-dir output/smp_teacher_rollouts/d29_t1_a
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import cast

import numpy as np
import torch
import tyro

from mjlab.envs import ManagerBasedRlEnv
from mjlab.rl import MjlabOnPolicyRunner, RslRlVecEnvWrapper
from mjlab.sensor import ContactSensor
from mjlab.tasks.registry import load_env_cfg, load_rl_cfg, load_runner_cls
from mjlab.utils.torch import configure_torch_backends
from nazarite.config.train_config.train_algorithm.smp.teacher.reference import (
  ReferenceMotionCommand,
  ReferenceMotionCommandCfg,
)


@dataclass(frozen=True)
class ExportConfig:
  """Settings for one deterministic, single-environment teacher rollout."""

  checkpoint_file: str
  """Local RSL-RL checkpoint containing the trained teacher actor."""

  output_dir: str = "output/smp_teacher_rollouts"
  """Directory receiving ``teacher_rollout.npz`` and ``summary.json``."""

  reference_file: str | None = None
  """Optional preprocessed reference NPZ; otherwise use the task default."""

  max_steps: int = 500
  """Maximum policy steps to execute. The reference termination usually ends it earlier."""

  seed: int = 42
  device: str | None = None


def _numpy(value: torch.Tensor) -> np.ndarray:
  """Detach one simulator tensor without retaining GPU memory."""
  return value.detach().cpu().numpy().copy()


def _finite(value: torch.Tensor) -> bool:
  return bool(torch.isfinite(value).all().item())


def _contact_force_per_foot(sensor: ContactSensor, num_feet: int) -> torch.Tensor:
  """Reduce contact-sensor slots to one force magnitude per foot."""
  if sensor.data.force is None:
    raise RuntimeError("feet_ground_contact must provide force data")
  force = torch.linalg.vector_norm(sensor.data.force, dim=-1)
  # Depending on the sensor backend, ``num_slots=1`` may remain as an extra
  # dimension.  Max-reduce all dimensions between environment and foot.
  while force.ndim > 2:
    force = force.amax(dim=-1)
  if force.shape[1] != num_feet:
    force = force.reshape(force.shape[0], num_feet, -1).amax(dim=-1)
  return force


class _RolloutCollector:
  """Read the physical state and reference state from one environment."""

  def __init__(self, env: ManagerBasedRlEnv):
    self.env = env
    self.robot = env.scene["robot"]
    reference = env.command_manager.get_term("reference")
    if not isinstance(reference, ReferenceMotionCommand):
      raise TypeError("the task reference command is not ReferenceMotionCommand")
    self.reference = reference
    sensor = env.scene["feet_ground_contact"]
    if not isinstance(sensor, ContactSensor):
      raise TypeError("feet_ground_contact is not a ContactSensor")
    self.contact_sensor = sensor

    indexing = self.robot.indexing
    self.joint_ids = reference.joint_ids
    self.site_ids = reference.site_ids
    self.qpos_ids = torch.cat((indexing.free_joint_q_adr, indexing.joint_q_adr[self.joint_ids]))
    self.qvel_ids = torch.cat((indexing.free_joint_v_adr, indexing.joint_v_adr[self.joint_ids]))

  def snapshot(self, action: torch.Tensor, reward: torch.Tensor, done: torch.Tensor) -> dict[str, torch.Tensor]:
    """Return a detached one-environment snapshot."""
    robot_data = self.robot.data
    reference = self.reference
    foot_pos_base = reference._actual_foot_pos_base()
    force = _contact_force_per_foot(self.contact_sensor, len(reference.cfg.foot_site_names))
    actual_contact = (force >= 5.0).to(dtype=torch.float32)

    qpos = robot_data.data.qpos[:, self.qpos_ids]
    qvel = robot_data.data.qvel[:, self.qvel_ids]
    state = torch.cat(
      (
        qpos,
        qvel,
        robot_data.actuator_force,
        robot_data.qfrc_actuator,
        robot_data.joint_pos_target[:, self.joint_ids],
        action,
        reward[:, None],
        done[:, None].to(dtype=torch.float32),
      ),
      dim=-1,
    )
    physics_valid = torch.isfinite(state).all(dim=-1)

    return {
      "qpos": qpos,
      "qvel": qvel,
      "root_pos": robot_data.root_link_pos_w,
      "root_quat_wxyz": robot_data.root_link_quat_w,
      "root_lin_vel_w": robot_data.root_link_lin_vel_w,
      "root_ang_vel_b": robot_data.root_link_ang_vel_b,
      "joint_pos": robot_data.joint_pos[:, self.joint_ids],
      "joint_vel": robot_data.joint_vel[:, self.joint_ids],
      "joint_pos_target": robot_data.joint_pos_target[:, self.joint_ids],
      "foot_pos_base": foot_pos_base,
      "actuator_force": robot_data.actuator_force,
      "qfrc_actuator": robot_data.qfrc_actuator,
      "action": action,
      "reward": reward,
      "done": done.to(dtype=torch.float32),
      "physics_valid": physics_valid.to(dtype=torch.float32),
      "reference_joint_pos": reference.joint_pos,
      "reference_joint_vel": reference.joint_vel,
      "reference_root_pos_w": reference.root_pos_w,
      "reference_root_quat_wxyz": reference.root_quat_w,
      "reference_root_lin_vel_b": reference.root_lin_vel_b,
      "reference_foot_target_base": reference.foot_target_base,
      "reference_contact": reference.contact,
      "actual_contact": actual_contact,
      "contact_force": force,
      "reference_phase": reference.phase,
    }


def _stack_snapshots(snapshots: list[dict[str, torch.Tensor]]) -> dict[str, np.ndarray]:
  """Stack the first vectorized environment dimension and remove it."""
  result: dict[str, np.ndarray] = {}
  for key in snapshots[0]:
    values = torch.cat([snapshot[key] for snapshot in snapshots], dim=0)
    result[key] = _numpy(values)
  return result


def run_export(cfg: ExportConfig) -> dict[str, object]:
  """Load a teacher checkpoint and export one physical rollout."""
  if cfg.max_steps < 1:
    raise ValueError("max_steps must be positive")
  checkpoint = Path(cfg.checkpoint_file).expanduser().resolve()
  if not checkpoint.is_file():
    raise FileNotFoundError(f"checkpoint file not found: {checkpoint}")

  configure_torch_backends()
  device = cfg.device or ("cuda:0" if torch.cuda.is_available() else "cpu")
  env_cfg = load_env_cfg("Nazarite-SMP-Teacher-Go2")
  agent_cfg = load_rl_cfg("Nazarite-SMP-Teacher-Go2")
  env_cfg.scene.num_envs = 1
  env_cfg.seed = cfg.seed
  env_cfg.auto_reset = False
  env_cfg.observations["actor"].enable_corruption = False
  if cfg.reference_file is not None:
    reference_cfg = cast(ReferenceMotionCommandCfg, env_cfg.commands["reference"])
    reference_cfg.motion_file = str(
      Path(cfg.reference_file).expanduser().resolve()
    )

  raw_env = ManagerBasedRlEnv(cfg=env_cfg, device=device)
  env = RslRlVecEnvWrapper(raw_env, clip_actions=agent_cfg.clip_actions)
  output_dir = Path(cfg.output_dir).expanduser().resolve()
  output_dir.mkdir(parents=True, exist_ok=True)

  try:
    runner_cls = load_runner_cls("Nazarite-SMP-Teacher-Go2") or MjlabOnPolicyRunner
    runner = runner_cls(env, asdict(agent_cfg), device=device)
    runner.load(str(checkpoint), load_cfg={"actor": True}, strict=True, map_location=device)
    policy = runner.get_inference_policy(device=device)
    collector = _RolloutCollector(raw_env)

    obs = env.get_observations()
    zero_action = torch.zeros((1, env.num_actions), device=device)
    zero_reward = torch.zeros(1, device=device)
    zero_done = torch.zeros(1, dtype=torch.bool, device=device)
    snapshots = [collector.snapshot(zero_action, zero_reward, zero_done)]
    terminated = False
    truncated = False

    for _ in range(cfg.max_steps):
      with torch.inference_mode():
        action = policy(obs)
      obs, reward, dones, _extras = env.step(action)
      terminated = bool(raw_env.reset_terminated[0].item())
      truncated = bool(raw_env.reset_time_outs[0].item())
      snapshots.append(collector.snapshot(raw_env.action_manager.action, reward, dones.bool()))
      if terminated or truncated:
        break

    arrays = _stack_snapshots(snapshots)
    arrays["fps"] = np.asarray(1.0 / raw_env.step_dt, dtype=np.float32)
    arrays["smp_joint_order"] = np.asarray(collector.reference.cfg.joint_names)
    arrays["smp_leg_order"] = np.asarray(collector.reference.cfg.foot_site_names)
    arrays["checkpoint"] = np.asarray(str(checkpoint))
    npz_path = output_dir / "teacher_rollout.npz"
    np.savez_compressed(npz_path, **arrays)  # pyright: ignore[reportArgumentType]

    valid = arrays["physics_valid"].astype(bool)
    summary: dict[str, object] = {
      "task": "Nazarite-SMP-Teacher-Go2",
      "checkpoint": str(checkpoint),
      "reference_file": str(collector.reference.cfg.motion_file),
      "device": device,
      "fps": float(1.0 / raw_env.step_dt),
      "num_frames": len(snapshots),
      "num_policy_steps": int(len(snapshots) - 1),
      "terminated": terminated,
      "truncated": truncated,
      "physics_valid_frames": int(valid.sum()),
      "physics_valid_fraction": float(valid.mean()),
      "mean_reward": float(arrays["reward"].mean()),
      "max_joint_position_error": float(
        np.linalg.norm(arrays["joint_pos"] - arrays["reference_joint_pos"], axis=-1).max()
      ),
      "output": str(npz_path),
    }
    summary_path = output_dir / "summary.json"
    with summary_path.open("w", encoding="utf-8") as file:
      json.dump(summary, file, indent=2)
    print(json.dumps(summary, indent=2, ensure_ascii=False))
    print(f"Wrote: {npz_path}")
    print(f"Wrote: {summary_path}")
    return summary
  finally:
    env.close()


def main() -> None:
  """CLI entry point."""
  import nazarite  # noqa: F401  # Register the task before loading its config.

  run_export(tyro.cli(ExportConfig))


if __name__ == "__main__":
  main()
